export const QUESTIONS = [
  {
    id: 'pagination',
    title: 'Pagination',
    path: '/pagination',
    category: 'Data Display',
    difficulty: 'Easy',
    description: 'Client-side paginated list with prev/next controls, page number buttons, and ellipsis gaps.',
    files: [
      'Pagination/Pagination.jsx',
      'Pagination/Pagination.module.css',
      'Pagination/usePagination.js',
    ],
  },
  {
    id: 'dark-mode',
    title: 'Dark Mode',
    path: '/dark-mode',
    category: 'Global Feature',
    difficulty: 'Easy',
    description: 'Theme toggle with localStorage persistence and prefers-color-scheme detection on first visit.',
    files: [
      'DarkMode/DarkMode.jsx',
      'DarkMode/DarkMode.module.css',
    ],
  },
  {
    id: 'toast',
    title: 'Reusable Toast',
    path: '/toast',
    category: 'UI Component',
    difficulty: 'Medium',
    description: 'Notification system with 4 types, auto-dismiss, progress bar, and multiple position variants.',
    files: [
      'Toast/ToastDemo.jsx',
      'Toast/ToastDemo.module.css',
    ],
  },
  {
    id: 'accordion',
    title: 'Accordion',
    path: '/accordion',
    category: 'UI Component',
    difficulty: 'Easy',
    description: 'Collapsible sections with single-open and multi-open modes. Full keyboard navigation.',
    files: [
      'Accordion/Accordion.jsx',
      'Accordion/Accordion.module.css',
      'Accordion/useAccordion.js',
    ],
  },
  {
    id: 'tabs',
    title: 'Tabs Component',
    path: '/tabs',
    category: 'UI Component',
    difficulty: 'Easy',
    description: 'Accessible tab strip with roving tabindex, arrow key navigation, and ARIA tablist pattern.',
    files: [
      'Tabs/Tabs.jsx',
      'Tabs/Tabs.module.css',
      'Tabs/useTabs.js',
    ],
  },
  {
    id: 'otp-input',
    title: 'OTP Input',
    path: '/otp-input',
    category: 'Form Control',
    difficulty: 'Medium',
    description: '6-digit OTP input with auto-advance, backspace navigation, and paste support.',
    files: [
      'OTPInput/OTPInput.jsx',
      'OTPInput/OTPInput.module.css',
      'OTPInput/useOTPInput.js',
    ],
  },
  {
    id: 'progress-bar',
    title: 'Progress Bar',
    path: '/progress-bar',
    category: 'UI Component',
    difficulty: 'Easy',
    description: 'Determinate, indeterminate, and stepped progress bar variants with ARIA progressbar role.',
    files: [
      'ProgressBar/ProgressBarDemo.jsx',
      'ProgressBar/ProgressBar.jsx',
      'ProgressBar/ProgressBar.module.css',
    ],
  },
  {
    id: 'parallel-progress',
    title: 'Parallel Progress Bar',
    path: '/parallel-progress',
    category: 'UI Component',
    difficulty: 'Medium',
    description: 'Multiple independent progress bars running concurrently using requestAnimationFrame.',
    files: [
      'ParallelProgressBar/ParallelProgressBar.jsx',
      'ParallelProgressBar/ParallelProgressBar.module.css',
      'ParallelProgressBar/useProgressTimer.js',
    ],
  },
  {
    id: 'price-range-slider',
    title: 'Price Range Slider',
    path: '/price-range-slider',
    category: 'Form Control',
    difficulty: 'Medium',
    description: 'Dual-thumb range slider with min/max clamping, custom track fill, and keyboard support.',
    files: [
      'PriceRangeSlider/PriceRangeSlider.jsx',
      'PriceRangeSlider/PriceRangeSlider.module.css',
      'PriceRangeSlider/usePriceRange.js',
    ],
  },
  {
    id: 'multiselect',
    title: 'Multiselect Dropdown',
    path: '/multiselect',
    category: 'Form Control',
    difficulty: 'Medium',
    description: 'Dropdown with checkboxes, search filter, select-all, chip display, and keyboard navigation.',
    files: [
      'MultiselectDropdown/MultiselectDropdown.jsx',
      'MultiselectDropdown/MultiselectDropdown.module.css',
      'MultiselectDropdown/useMultiselect.js',
    ],
  },
  {
    id: 'searchable-dropdown',
    title: 'Searchable Dropdown',
    path: '/searchable-dropdown',
    category: 'Form Control',
    difficulty: 'Medium',
    description: 'Combobox with debounced filtering, keyboard navigation, and aria-activedescendant pattern.',
    files: [
      'SearchableDropdown/SearchableDropdown.jsx',
      'SearchableDropdown/SearchableDropdown.module.css',
      'SearchableDropdown/useSearchableDropdown.js',
    ],
  },
  {
    id: 'carousel',
    title: 'Carousel',
    path: '/carousel',
    category: 'UI Component',
    difficulty: 'Medium',
    description: 'Slide carousel with autoplay, pause-on-hover, dot indicators, and touch swipe support.',
    files: [
      'Carousel/Carousel.jsx',
      'Carousel/Carousel.module.css',
      'Carousel/useCarousel.js',
    ],
  },
  {
    id: 'infinite-scroll',
    title: 'Infinite Scroll',
    path: '/infinite-scroll',
    category: 'Data Display',
    difficulty: 'Medium',
    description: 'List with IntersectionObserver sentinel, skeleton loaders, and end-of-data state handling.',
    files: [
      'InfiniteScroll/InfiniteScroll.jsx',
      'InfiniteScroll/InfiniteScroll.module.css',
      'InfiniteScroll/useInfiniteScroll.js',
    ],
  },
  {
    id: 'all-pagination',
    title: 'All Pagination Types',
    path: '/all-pagination',
    category: 'Data Display',
    difficulty: 'Medium',
    description: 'Page number, Load More, and Jump-to-page pagination patterns side by side.',
    files: [
      'AllPagination/AllPagination.jsx',
      'AllPagination/AllPagination.module.css',
      'AllPagination/useLoadMore.js',
    ],
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    path: '/tic-tac-toe',
    category: 'Game',
    difficulty: 'Easy',
    description: '2-player Tic Tac Toe with win/draw detection, move history time-travel, and restart.',
    files: [
      'TicTacToe/TicTacToe.jsx',
      'TicTacToe/TicTacToe.module.css',
      'TicTacToe/useTicTacToe.js',
    ],
  },
  {
    id: 'nested-file-system',
    title: 'Nested File System',
    path: '/nested-file-system',
    category: 'Recursive UI',
    difficulty: 'Hard',
    description: 'File explorer tree with expand/collapse, selection, and full ARIA tree keyboard navigation.',
    files: [
      'NestedFileSystem/FileTree.jsx',
      'NestedFileSystem/FileTree.module.css',
      'NestedFileSystem/useFileTree.js',
      'NestedFileSystem/mockData.js',
    ],
  },
  {
    id: 'nested-comments',
    title: 'Nested Comments',
    path: '/nested-comments',
    category: 'Recursive UI',
    difficulty: 'Medium',
    description: 'Reddit-style recursive comment threads with replies, collapse/expand, and vote buttons.',
    files: [
      'NestedComments/CommentThread.jsx',
      'NestedComments/CommentThread.module.css',
      'NestedComments/useComments.js',
      'NestedComments/mockComments.js',
    ],
  },
  {
    id: 'tree-checkbox',
    title: 'Tree Navigation + Checkbox',
    path: '/tree-checkbox',
    category: 'Recursive UI',
    difficulty: 'Hard',
    description: 'Tree with tri-state checkboxes — parent/child propagation and indeterminate state.',
    files: [
      'TreeCheckbox/TreeCheckbox.jsx',
      'TreeCheckbox/TreeCheckbox.module.css',
      'TreeCheckbox/useTreeCheckbox.js',
      'TreeCheckbox/mockTree.js',
    ],
  },
  {
    id: 'complex-sidebar',
    title: 'Complex Sidebar',
    path: '/complex-sidebar',
    category: 'Navigation',
    difficulty: 'Hard',
    description: 'Multi-level collapsible sidebar with overlay mode, focus trap, and responsive behaviour.',
    files: [
      'ComplexSidebar/ComplexSidebar.jsx',
      'ComplexSidebar/ComplexSidebar.module.css',
    ],
  },
  {
    id: 'jira-board',
    title: 'Jira Board (Drag & Drop)',
    path: '/jira-board',
    category: 'Interaction',
    difficulty: 'Hard',
    description: 'Kanban board with HTML5 DnD — drag cards between columns, keyboard move fallback.',
    files: [
      'JiraBoard/JiraBoard.jsx',
      'JiraBoard/JiraBoard.module.css',
      'JiraBoard/useKanban.js',
      'JiraBoard/mockBoard.js',
    ],
  },
  {
    id: 'file-explorer',
    title: 'File Explorer',
    path: '/file-explorer',
    category: 'Navigation',
    difficulty: 'Medium',
    description: 'Directory-style file browser — click folders to enter, breadcrumb to go back. O(1) path-as-object-reference navigation with unlimited nesting depth.',
    files: [
      'FileExplorer/FileExplorer.jsx',
      'FileExplorer/FileExplorer.module.css',
      'FileExplorer/useFileExplorer.js',
      'FileExplorer/mockData.js',
    ],
  },
  {
    id: 'form-builder',
    title: 'Form Builder',
    path: '/form-builder',
    category: 'Interaction',
    difficulty: 'Hard',
    description: 'Configure and add text, number, email, textarea, checkbox, select, and radio fields. Live preview with controlled inputs; submit logs all values as an object.',
    files: [
      'FormBuilder/FormBuilder.jsx',
      'FormBuilder/FormBuilder.module.css',
      'FormBuilder/useFormBuilder.js',
    ],
  },
  {
    id: 'state-management',
    title: 'State Management Showdown',
    path: '/state-management',
    category: 'State & Data Fetching',
    difficulty: 'Hard',
    description: '7 ways to fetch and display posts from a real API — fetch, Axios, Context API, Redux Classic, RTK, RTK Query, and Zustand. Includes live comparison table.',
    files: [
      'StateManagement/StateManagement.jsx',
      'StateManagement/StateManagement.module.css',
      'StateManagement/components/PostsList.jsx',
      'StateManagement/variants/FetchVariant.jsx',
      'StateManagement/variants/AxiosVariant.jsx',
      'StateManagement/variants/ContextVariant/PostsContext.jsx',
      'StateManagement/variants/ContextVariant/ContextVariant.jsx',
      'StateManagement/variants/ReduxClassicVariant/ReduxClassicVariant.jsx',
      'StateManagement/variants/RTKVariant/RTKVariant.jsx',
      'StateManagement/variants/RTKQueryVariant/RTKQueryVariant.jsx',
      'StateManagement/variants/ZustandVariant/ZustandVariant.jsx',
    ],
  },
];
