export const QUESTIONS = [
  {
    id: 'pagination',
    title: 'Pagination',
    path: '/pagination',
    category: 'Data Display',
    difficulty: 'Easy',
    description: 'Client-side paginated list with prev/next controls, page number buttons, and ellipsis gaps.',
  },
  {
    id: 'dark-mode',
    title: 'Dark Mode',
    path: '/dark-mode',
    category: 'Global Feature',
    difficulty: 'Easy',
    description: 'Theme toggle with localStorage persistence and prefers-color-scheme detection on first visit.',
  },
  {
    id: 'toast',
    title: 'Reusable Toast',
    path: '/toast',
    category: 'UI Component',
    difficulty: 'Medium',
    description: 'Notification system with 4 types, auto-dismiss, progress bar, and multiple position variants.',
  },
  {
    id: 'accordion',
    title: 'Accordion',
    path: '/accordion',
    category: 'UI Component',
    difficulty: 'Easy',
    description: 'Collapsible sections with single-open and multi-open modes. Full keyboard navigation.',
  },
  {
    id: 'tabs',
    title: 'Tabs Component',
    path: '/tabs',
    category: 'UI Component',
    difficulty: 'Easy',
    description: 'Accessible tab strip with roving tabindex, arrow key navigation, and ARIA tablist pattern.',
  },
  {
    id: 'otp-input',
    title: 'OTP Input',
    path: '/otp-input',
    category: 'Form Control',
    difficulty: 'Medium',
    description: '6-digit OTP input with auto-advance, backspace navigation, and paste support.',
  },
  {
    id: 'progress-bar',
    title: 'Progress Bar',
    path: '/progress-bar',
    category: 'UI Component',
    difficulty: 'Easy',
    description: 'Determinate, indeterminate, and stepped progress bar variants with ARIA progressbar role.',
  },
  {
    id: 'parallel-progress',
    title: 'Parallel Progress Bar',
    path: '/parallel-progress',
    category: 'UI Component',
    difficulty: 'Medium',
    description: 'Multiple independent progress bars running concurrently using requestAnimationFrame.',
  },
  {
    id: 'price-range-slider',
    title: 'Price Range Slider',
    path: '/price-range-slider',
    category: 'Form Control',
    difficulty: 'Medium',
    description: 'Dual-thumb range slider with min/max clamping, custom track fill, and keyboard support.',
  },
  {
    id: 'multiselect',
    title: 'Multiselect Dropdown',
    path: '/multiselect',
    category: 'Form Control',
    difficulty: 'Medium',
    description: 'Dropdown with checkboxes, search filter, select-all, chip display, and keyboard navigation.',
  },
  {
    id: 'searchable-dropdown',
    title: 'Searchable Dropdown',
    path: '/searchable-dropdown',
    category: 'Form Control',
    difficulty: 'Medium',
    description: 'Combobox with debounced filtering, keyboard navigation, and aria-activedescendant pattern.',
  },
  {
    id: 'carousel',
    title: 'Carousel',
    path: '/carousel',
    category: 'UI Component',
    difficulty: 'Medium',
    description: 'Slide carousel with autoplay, pause-on-hover, dot indicators, and touch swipe support.',
  },
  {
    id: 'infinite-scroll',
    title: 'Infinite Scroll',
    path: '/infinite-scroll',
    category: 'Data Display',
    difficulty: 'Medium',
    description: 'List with IntersectionObserver sentinel, skeleton loaders, and end-of-data state handling.',
  },
  {
    id: 'all-pagination',
    title: 'All Pagination Types',
    path: '/all-pagination',
    category: 'Data Display',
    difficulty: 'Medium',
    description: 'Page number, Load More, and Jump-to-page pagination patterns side by side.',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    path: '/tic-tac-toe',
    category: 'Game',
    difficulty: 'Easy',
    description: '2-player Tic Tac Toe with win/draw detection, move history time-travel, and restart.',
  },
  {
    id: 'nested-file-system',
    title: 'Nested File System',
    path: '/nested-file-system',
    category: 'Recursive UI',
    difficulty: 'Hard',
    description: 'File explorer tree with expand/collapse, selection, and full ARIA tree keyboard navigation.',
  },
  {
    id: 'nested-comments',
    title: 'Nested Comments',
    path: '/nested-comments',
    category: 'Recursive UI',
    difficulty: 'Medium',
    description: 'Reddit-style recursive comment threads with replies, collapse/expand, and vote buttons.',
  },
  {
    id: 'tree-checkbox',
    title: 'Tree Navigation + Checkbox',
    path: '/tree-checkbox',
    category: 'Recursive UI',
    difficulty: 'Hard',
    description: 'Tree with tri-state checkboxes — parent/child propagation and indeterminate state.',
  },
  {
    id: 'complex-sidebar',
    title: 'Complex Sidebar',
    path: '/complex-sidebar',
    category: 'Navigation',
    difficulty: 'Hard',
    description: 'Multi-level collapsible sidebar with overlay mode, focus trap, and responsive behaviour.',
  },
  {
    id: 'jira-board',
    title: 'Jira Board (Drag & Drop)',
    path: '/jira-board',
    category: 'Interaction',
    difficulty: 'Hard',
    description: 'Kanban board with HTML5 DnD — drag cards between columns, keyboard move fallback.',
  },
  {
    id: 'file-explorer',
    title: 'File Explorer',
    path: '/file-explorer',
    category: 'Navigation',
    difficulty: 'Medium',
    description: 'Directory-style file browser — click folders to enter, breadcrumb to go back. O(1) path-as-object-reference navigation with unlimited nesting depth.',
  },
  {
    id: 'form-builder',
    title: 'Form Builder',
    path: '/form-builder',
    category: 'Interaction',
    difficulty: 'Hard',
    description: 'Configure and add text, number, email, textarea, checkbox, select, and radio fields. Live preview with controlled inputs; submit logs all values as an object.',
  },
  {
    id: 'state-management',
    title: 'State Management Showdown',
    path: '/state-management',
    category: 'State & Data Fetching',
    difficulty: 'Hard',
    description: '7 ways to fetch and display posts from a real API — fetch, Axios, Context API, Redux Classic, RTK, RTK Query, and Zustand. Includes live comparison table.',
  },
];
